Record = {'personal' :{'id': 101, 'name': 'Amit', 'age' : 23},
    'exam' :{'total': 550, 'perc': 91.6, 'grade' : 'A'}}
print("Record...")
print(Record)
print("personal...")
print(Record['personal'])
print("exam...")
print(Record['exam'])
print("Dictionary \'personal\' elements...")
print(Record['personal']['id'])
print(Record['personal']['name'])
print(Record['personal']['age'])
print("Dictionary \'exam\' elements...")
print(Record['exam']['total'])
print(Record['exam']['perc'])
print(Record['exam']['grade'])
